//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Sdk.PluginRegistration.Entities
{
	
	/// <summary>
	/// Contains predefined customer support terms that can be used to created entitlements for customers.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("entitlementtemplate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class EntitlementTemplate : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string AllocationTypeCode = "allocationtypecode";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DecreaseRemainingOn = "decreaseremainingon";
			public const string Description = "description";
			public const string EndDate = "enddate";
			public const string EntitlementTemplateId = "entitlementtemplateid";
			public const string Id = "entitlementtemplateid";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string KbAccessLevel = "kbaccesslevel";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string RestrictCaseCreation = "restrictcasecreation";
			public const string SLAId = "slaid";
			public const string StartDate = "startdate";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TotalTerms = "totalterms";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string entitlementtemplate_organization = "entitlementtemplate_organization";
			public const string lk_entitlementtemplate_createdby = "lk_entitlementtemplate_createdby";
			public const string lk_entitlementtemplate_createdonbehalfby = "lk_entitlementtemplate_createdonbehalfby";
			public const string lk_entitlementtemplate_modifiedby = "lk_entitlementtemplate_modifiedby";
			public const string lk_entitlementtemplate_modifiedonbehalfby = "lk_entitlementtemplate_modifiedonbehalfby";
			public const string sla_entitlementtemplate = "sla_entitlementtemplate";
			public const string TransactionCurrency_entitlementtemplate = "TransactionCurrency_entitlementtemplate";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public EntitlementTemplate() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "entitlementtemplate";
		
		public const string PrimaryIdAttribute = "entitlementtemplateid";
		
		public const string PrimaryNameAttribute = "name";
		
		public const int EntityTypeCode = 9702;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Select whether the entitlement allocation is based on number of cases or number of hours.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allocationtypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AllocationTypeCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("allocationtypecode");
			}
			set
			{
				this.OnPropertyChanging("AllocationTypeCode");
				this.SetAttributeValue("allocationtypecode", value);
				this.OnPropertyChanged("AllocationTypeCode");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Information about whether to decrease the remaining terms when the case is created or when it is resolved
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decreaseremainingon")]
		public Microsoft.Xrm.Sdk.OptionSetValue DecreaseRemainingOn
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("decreaseremainingon");
			}
			set
			{
				this.OnPropertyChanging("DecreaseRemainingOn");
				this.SetAttributeValue("decreaseremainingon", value);
				this.OnPropertyChanged("DecreaseRemainingOn");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the account, such as an excerpt from the company's website.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Enter the date and time when the entitlement ends.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("enddate")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("enddate");
			}
			set
			{
				this.OnPropertyChanging("EndDate");
				this.SetAttributeValue("enddate", value);
				this.OnPropertyChanged("EndDate");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitlementtemplateid")]
		public System.Nullable<System.Guid> EntitlementTemplateId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entitlementtemplateid");
			}
			set
			{
				this.OnPropertyChanging("EntitlementTemplateId");
				this.SetAttributeValue("entitlementtemplateid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("EntitlementTemplateId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitlementtemplateid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.EntitlementTemplateId = value;
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the contact with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Select the access someone will have to the knowledge base on the portal.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kbaccesslevel")]
		public Microsoft.Xrm.Sdk.OptionSetValue KbAccessLevel
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("kbaccesslevel");
			}
			set
			{
				this.OnPropertyChanging("KbAccessLevel");
				this.SetAttributeValue("kbaccesslevel", value);
				this.OnPropertyChanged("KbAccessLevel");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type a descriptive name for the entitlement template.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Tells whether case creation is restricted based on entitlement terms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("restrictcasecreation")]
		public System.Nullable<bool> RestrictCaseCreation
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("restrictcasecreation");
			}
			set
			{
				this.OnPropertyChanging("RestrictCaseCreation");
				this.SetAttributeValue("restrictcasecreation", value);
				this.OnPropertyChanged("RestrictCaseCreation");
			}
		}
		
		/// <summary>
		/// Choose the service level agreement (SLA) associated with the entitlement.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			set
			{
				this.OnPropertyChanging("SLAId");
				this.SetAttributeValue("slaid", value);
				this.OnPropertyChanged("SLAId");
			}
		}
		
		/// <summary>
		/// Enter the date and time when the entitlement begins.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("startdate")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("startdate");
			}
			set
			{
				this.OnPropertyChanging("StartDate");
				this.SetAttributeValue("startdate", value);
				this.OnPropertyChanged("StartDate");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Type the total number of entitlement terms.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("totalterms")]
		public System.Nullable<decimal> TotalTerms
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("totalterms");
			}
			set
			{
				this.OnPropertyChanging("TotalTerms");
				this.SetAttributeValue("totalterms", value);
				this.OnPropertyChanged("TotalTerms");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.ActivityPointer> entitlementtemplate_ActivityPointers
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ActivityPointer>("entitlementtemplate_ActivityPointers", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_ActivityPointers");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ActivityPointer>("entitlementtemplate_ActivityPointers", null, value);
				this.OnPropertyChanged("entitlementtemplate_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Annotations")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Annotation> entitlementtemplate_Annotations
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Annotation>("entitlementtemplate_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Annotations");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Annotation>("entitlementtemplate_Annotations", null, value);
				this.OnPropertyChanged("entitlementtemplate_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Appointments")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Appointment> entitlementtemplate_Appointments
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Appointment>("entitlementtemplate_Appointments", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Appointments");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Appointment>("entitlementtemplate_Appointments", null, value);
				this.OnPropertyChanged("entitlementtemplate_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation> entitlementtemplate_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation>("entitlementtemplate_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_AsyncOperations");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation>("entitlementtemplate_AsyncOperations", null, value);
				this.OnPropertyChanged("entitlementtemplate_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure> entitlementtemplate_BulkDeleteFailures
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure>("entitlementtemplate_BulkDeleteFailures", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_BulkDeleteFailures");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure>("entitlementtemplate_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("entitlementtemplate_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord> entitlementtemplate_DuplicateBaseRecord
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord>("entitlementtemplate_DuplicateBaseRecord", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_DuplicateBaseRecord");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord>("entitlementtemplate_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("entitlementtemplate_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord> entitlementtemplate_DuplicateMatchingRecord
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord>("entitlementtemplate_DuplicateMatchingRecord", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_DuplicateMatchingRecord");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.DuplicateRecord>("entitlementtemplate_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("entitlementtemplate_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Emails")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Email> entitlementtemplate_Emails
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Email>("entitlementtemplate_Emails", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Emails");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Email>("entitlementtemplate_Emails", null, value);
				this.OnPropertyChanged("entitlementtemplate_Emails");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_entitlementchannel_entitlementtemplateid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_entitlementchannel_entitlementtemplateid")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.EntitlementTemplateChannel> entitlementtemplate_entitlementchannel_entitlementtemplateid
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.EntitlementTemplateChannel>("entitlementtemplate_entitlementchannel_entitlementtemplateid", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_entitlementchannel_entitlementtemplateid");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.EntitlementTemplateChannel>("entitlementtemplate_entitlementchannel_entitlementtemplateid", null, value);
				this.OnPropertyChanged("entitlementtemplate_entitlementchannel_entitlementtemplateid");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Faxes")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Fax> entitlementtemplate_Faxes
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Fax>("entitlementtemplate_Faxes", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Faxes");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Fax>("entitlementtemplate_Faxes", null, value);
				this.OnPropertyChanged("entitlementtemplate_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_IncidentResolutions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_IncidentResolutions")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.IncidentResolution> entitlementtemplate_IncidentResolutions
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.IncidentResolution>("entitlementtemplate_IncidentResolutions", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_IncidentResolutions");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.IncidentResolution>("entitlementtemplate_IncidentResolutions", null, value);
				this.OnPropertyChanged("entitlementtemplate_IncidentResolutions");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Letters")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Letter> entitlementtemplate_Letters
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Letter>("entitlementtemplate_Letters", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Letters");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Letter>("entitlementtemplate_Letters", null, value);
				this.OnPropertyChanged("entitlementtemplate_Letters");
			}
		}
		
		/// <summary>
		/// 1:N EntitlementTemplate_MailboxTrackingFolder
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("EntitlementTemplate_MailboxTrackingFolder")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder> EntitlementTemplate_MailboxTrackingFolder
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder>("EntitlementTemplate_MailboxTrackingFolder", null);
			}
			set
			{
				this.OnPropertyChanging("EntitlementTemplate_MailboxTrackingFolder");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder>("EntitlementTemplate_MailboxTrackingFolder", null, value);
				this.OnPropertyChanged("EntitlementTemplate_MailboxTrackingFolder");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_OpportunityCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_OpportunityCloses")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.OpportunityClose> entitlementtemplate_OpportunityCloses
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.OpportunityClose>("entitlementtemplate_OpportunityCloses", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_OpportunityCloses");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.OpportunityClose>("entitlementtemplate_OpportunityCloses", null, value);
				this.OnPropertyChanged("entitlementtemplate_OpportunityCloses");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_OrderCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_OrderCloses")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.OrderClose> entitlementtemplate_OrderCloses
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.OrderClose>("entitlementtemplate_OrderCloses", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_OrderCloses");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.OrderClose>("entitlementtemplate_OrderCloses", null, value);
				this.OnPropertyChanged("entitlementtemplate_OrderCloses");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.PhoneCall> entitlementtemplate_PhoneCalls
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PhoneCall>("entitlementtemplate_PhoneCalls", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_PhoneCalls");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PhoneCall>("entitlementtemplate_PhoneCalls", null, value);
				this.OnPropertyChanged("entitlementtemplate_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess> entitlementtemplate_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess>("entitlementtemplate_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess>("entitlementtemplate_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("entitlementtemplate_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_ProcessSession")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.ProcessSession> entitlementtemplate_ProcessSession
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ProcessSession>("entitlementtemplate_ProcessSession", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_ProcessSession");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ProcessSession>("entitlementtemplate_ProcessSession", null, value);
				this.OnPropertyChanged("entitlementtemplate_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_QuoteCloses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_QuoteCloses")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.QuoteClose> entitlementtemplate_QuoteCloses
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.QuoteClose>("entitlementtemplate_QuoteCloses", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_QuoteCloses");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.QuoteClose>("entitlementtemplate_QuoteCloses", null, value);
				this.OnPropertyChanged("entitlementtemplate_QuoteCloses");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.RecurringAppointmentMaster> entitlementtemplate_RecurringAppointmentMasters
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.RecurringAppointmentMaster>("entitlementtemplate_RecurringAppointmentMasters", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_RecurringAppointmentMasters");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.RecurringAppointmentMaster>("entitlementtemplate_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("entitlementtemplate_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.ServiceAppointment> entitlementtemplate_ServiceAppointments
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ServiceAppointment>("entitlementtemplate_ServiceAppointments", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_ServiceAppointments");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ServiceAppointment>("entitlementtemplate_ServiceAppointments", null, value);
				this.OnPropertyChanged("entitlementtemplate_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_SocialActivities")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.SocialActivity> entitlementtemplate_SocialActivities
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SocialActivity>("entitlementtemplate_SocialActivities", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_SocialActivities");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SocialActivity>("entitlementtemplate_SocialActivities", null, value);
				this.OnPropertyChanged("entitlementtemplate_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N EntitlementTemplate_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("EntitlementTemplate_SyncErrors")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.SyncError> EntitlementTemplate_SyncErrors
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SyncError>("EntitlementTemplate_SyncErrors", null);
			}
			set
			{
				this.OnPropertyChanging("EntitlementTemplate_SyncErrors");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SyncError>("EntitlementTemplate_SyncErrors", null, value);
				this.OnPropertyChanged("EntitlementTemplate_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_Tasks")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Task> entitlementtemplate_Tasks
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Task>("entitlementtemplate_Tasks", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_Tasks");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Task>("entitlementtemplate_Tasks", null, value);
				this.OnPropertyChanged("entitlementtemplate_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplate_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData> entitlementtemplate_UserEntityInstanceDatas
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData>("entitlementtemplate_UserEntityInstanceDatas", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplate_UserEntityInstanceDatas");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData>("entitlementtemplate_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("entitlementtemplate_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// 1:N entitlementtemplateid_RelationShip
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplateid_RelationShip")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Entitlement> entitlementtemplateid_RelationShip
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Entitlement>("entitlementtemplateid_RelationShip", null);
			}
			set
			{
				this.OnPropertyChanging("entitlementtemplateid_RelationShip");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Entitlement>("entitlementtemplateid_RelationShip", null, value);
				this.OnPropertyChanged("entitlementtemplateid_RelationShip");
			}
		}
		
		/// <summary>
		/// N:N product_entitlementtemplate_association
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("product_entitlementtemplate_association")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.Product> product_entitlementtemplate_association
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Product>("product_entitlementtemplate_association", null);
			}
			set
			{
				this.OnPropertyChanging("product_entitlementtemplate_association");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.Product>("product_entitlementtemplate_association", null, value);
				this.OnPropertyChanged("product_entitlementtemplate_association");
			}
		}
		
		/// <summary>
		/// N:1 entitlementtemplate_organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entitlementtemplate_organization")]
		public Xrm.Sdk.PluginRegistration.Entities.Organization entitlementtemplate_organization
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.Organization>("entitlementtemplate_organization", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_entitlementtemplate_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entitlementtemplate_createdby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_entitlementtemplate_createdby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_entitlementtemplate_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entitlementtemplate_createdonbehalfby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_entitlementtemplate_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_entitlementtemplate_createdonbehalfby");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_entitlementtemplate_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_entitlementtemplate_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entitlementtemplate_modifiedby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_entitlementtemplate_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_entitlementtemplate_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entitlementtemplate_modifiedonbehalfby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_entitlementtemplate_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_entitlementtemplate_modifiedonbehalfby");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_entitlementtemplate_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_entitlementtemplate_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 sla_entitlementtemplate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_entitlementtemplate")]
		public Xrm.Sdk.PluginRegistration.Entities.SLA sla_entitlementtemplate
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SLA>("sla_entitlementtemplate", null);
			}
			set
			{
				this.OnPropertyChanging("sla_entitlementtemplate");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SLA>("sla_entitlementtemplate", null, value);
				this.OnPropertyChanged("sla_entitlementtemplate");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_entitlementtemplate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_entitlementtemplate")]
		public Xrm.Sdk.PluginRegistration.Entities.TransactionCurrency TransactionCurrency_entitlementtemplate
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.TransactionCurrency>("TransactionCurrency_entitlementtemplate", null);
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrency_entitlementtemplate");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.TransactionCurrency>("TransactionCurrency_entitlementtemplate", null, value);
				this.OnPropertyChanged("TransactionCurrency_entitlementtemplate");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public EntitlementTemplate(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["entitlementtemplateid"] = base.Id;
                        break;
                    case "entitlementtemplateid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allocationtypecode")]
		public virtual entitlementtemplate_allocationtype? AllocationTypeCodeEnum
		{
			get
			{
				return ((entitlementtemplate_allocationtype?)(EntityOptionSetEnum.GetEnum(this, "allocationtypecode")));
			}
			set
			{
				AllocationTypeCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decreaseremainingon")]
		public virtual entitlementtemplate_decreaseremainingon? DecreaseRemainingOnEnum
		{
			get
			{
				return ((entitlementtemplate_decreaseremainingon?)(EntityOptionSetEnum.GetEnum(this, "decreaseremainingon")));
			}
			set
			{
				DecreaseRemainingOn = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kbaccesslevel")]
		public virtual entitlementtemplate_kbaccesslevel? KbAccessLevelEnum
		{
			get
			{
				return ((entitlementtemplate_kbaccesslevel?)(EntityOptionSetEnum.GetEnum(this, "kbaccesslevel")));
			}
			set
			{
				KbAccessLevel = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}