//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Sdk.PluginRegistration.Entities
{
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_callablecontext_msdyn_playbooktemplate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class msdyn_callablecontext_msdyn_playbooktemplate : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string msdyn_callablecontext_msdyn_playbooktemplateId = "msdyn_callablecontext_msdyn_playbooktemplateid";
			public const string Id = "msdyn_callablecontext_msdyn_playbooktemplateid";
			public const string msdyn_callablecontextid = "msdyn_callablecontextid";
			public const string msdyn_playbooktemplateid = "msdyn_playbooktemplateid";
			public const string VersionNumber = "versionnumber";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msdyn_callablecontext_msdyn_playbooktemplate() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_callablecontext_msdyn_playbooktemplate";
		
		public const string PrimaryIdAttribute = "msdyn_callablecontext_msdyn_playbooktemplateid";
		
		public const int EntityTypeCode = 10009;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_callablecontext_msdyn_playbooktemplateid")]
		public System.Nullable<System.Guid> msdyn_callablecontext_msdyn_playbooktemplateId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_callablecontext_msdyn_playbooktemplateid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_callablecontext_msdyn_playbooktemplateid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_callablecontextid")]
		public System.Nullable<System.Guid> msdyn_callablecontextid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_callablecontextid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_playbooktemplateid")]
		public System.Nullable<System.Guid> msdyn_playbooktemplateid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_playbooktemplateid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N msdyn_callablecontext_msdyn_playbooktemplate
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_callablecontext_msdyn_playbooktemplate")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.msdyn_callablecontext> msdyn_callablecontext_msdyn_playbooktemplate1
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.msdyn_callablecontext>("msdyn_callablecontext_msdyn_playbooktemplate", null);
			}
			set
			{
				this.OnPropertyChanging("msdyn_callablecontext_msdyn_playbooktemplate1");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.msdyn_callablecontext>("msdyn_callablecontext_msdyn_playbooktemplate", null, value);
				this.OnPropertyChanged("msdyn_callablecontext_msdyn_playbooktemplate1");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public msdyn_callablecontext_msdyn_playbooktemplate(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_callablecontext_msdyn_playbooktemplateid"] = base.Id;
                        break;
                    case "msdyn_callablecontext_msdyn_playbooktemplateid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}