//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Sdk.PluginRegistration.Entities
{
	
	/// <summary>
	/// Item in the sales literature collection.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("salesliteratureitem")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9369")]
	public partial class SalesLiteratureItem : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string Abstract = "abstract";
			public const string AttachedDocumentUrl = "attacheddocumenturl";
			public const string AuthorName = "authorname";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string DocumentBody = "documentbody";
			public const string FileName = "filename";
			public const string FileSize = "filesize";
			public const string FileTypeCode = "filetypecode";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IsCustomerViewable = "iscustomerviewable";
			public const string KeyWords = "keywords";
			public const string MimeType = "mimetype";
			public const string Mode = "mode";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string SalesLiteratureId = "salesliteratureid";
			public const string SalesLiteratureItemId = "salesliteratureitemid";
			public const string Id = "salesliteratureitemid";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string lk_salesliteratureitem_createdonbehalfby = "lk_salesliteratureitem_createdonbehalfby";
			public const string lk_salesliteratureitem_modifiedonbehalfby = "lk_salesliteratureitem_modifiedonbehalfby";
			public const string lk_salesliteratureitembase_createdby = "lk_salesliteratureitembase_createdby";
			public const string lk_salesliteratureitembase_modifiedby = "lk_salesliteratureitembase_modifiedby";
			public const string sales_literature_items = "sales_literature_items";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public SalesLiteratureItem() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "salesliteratureitem";
		
		public const string PrimaryIdAttribute = "salesliteratureitemid";
		
		public const string PrimaryNameAttribute = "title";
		
		public const int EntityTypeCode = 1070;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Abstract of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("abstract")]
		public string Abstract
		{
			get
			{
				return this.GetAttributeValue<string>("abstract");
			}
			set
			{
				this.OnPropertyChanging("Abstract");
				this.SetAttributeValue("abstract", value);
				this.OnPropertyChanged("Abstract");
			}
		}
		
		/// <summary>
		/// URL of the Website on which the document is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("attacheddocumenturl")]
		public string AttachedDocumentUrl
		{
			get
			{
				return this.GetAttributeValue<string>("attacheddocumenturl");
			}
			set
			{
				this.OnPropertyChanging("AttachedDocumentUrl");
				this.SetAttributeValue("attacheddocumenturl", value);
				this.OnPropertyChanged("AttachedDocumentUrl");
			}
		}
		
		/// <summary>
		/// Author name for the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("authorname")]
		public string AuthorName
		{
			get
			{
				return this.GetAttributeValue<string>("authorname");
			}
			set
			{
				this.OnPropertyChanging("AuthorName");
				this.SetAttributeValue("authorname", value);
				this.OnPropertyChanged("AuthorName");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the document was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the salesliteratureitem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the encoded contents of the sales literature document attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("documentbody")]
		public string DocumentBody
		{
			get
			{
				return this.GetAttributeValue<string>("documentbody");
			}
			set
			{
				this.OnPropertyChanging("DocumentBody");
				this.SetAttributeValue("documentbody", value);
				this.OnPropertyChanged("DocumentBody");
			}
		}
		
		/// <summary>
		/// File name of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filename")]
		public string FileName
		{
			get
			{
				return this.GetAttributeValue<string>("filename");
			}
			set
			{
				this.OnPropertyChanging("FileName");
				this.SetAttributeValue("filename", value);
				this.OnPropertyChanged("FileName");
			}
		}
		
		/// <summary>
		/// File size of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filesize")]
		public System.Nullable<int> FileSize
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("filesize");
			}
			set
			{
				this.OnPropertyChanging("FileSize");
				this.SetAttributeValue("filesize", value);
				this.OnPropertyChanged("FileSize");
			}
		}
		
		/// <summary>
		/// Select the file type of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filetypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue FileTypeCode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("filetypecode");
			}
			set
			{
				this.OnPropertyChanging("FileTypeCode");
				this.SetAttributeValue("filetypecode", value);
				this.OnPropertyChanged("FileTypeCode");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Tells whether the document can be shared with customers or is for internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomerviewable")]
		public System.Nullable<bool> IsCustomerViewable
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("iscustomerviewable");
			}
			set
			{
				this.OnPropertyChanging("IsCustomerViewable");
				this.SetAttributeValue("iscustomerviewable", value);
				this.OnPropertyChanged("IsCustomerViewable");
			}
		}
		
		/// <summary>
		/// Keywords to use for searches in documents.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keywords")]
		public string KeyWords
		{
			get
			{
				return this.GetAttributeValue<string>("keywords");
			}
			set
			{
				this.OnPropertyChanging("KeyWords");
				this.SetAttributeValue("keywords", value);
				this.OnPropertyChanged("KeyWords");
			}
		}
		
		/// <summary>
		/// Shows the file type of the sales literature document attachment, such as text or document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mimetype")]
		public string MimeType
		{
			get
			{
				return this.GetAttributeValue<string>("mimetype");
			}
			set
			{
				this.OnPropertyChanging("MimeType");
				this.SetAttributeValue("mimetype", value);
				this.OnPropertyChanged("MimeType");
			}
		}
		
		/// <summary>
		/// Defines the mode of the sales literature document attachment.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mode")]
		public string Mode
		{
			get
			{
				return this.GetAttributeValue<string>("mode");
			}
			set
			{
				this.OnPropertyChanging("Mode");
				this.SetAttributeValue("mode", value);
				this.OnPropertyChanged("Mode");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who last modified the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the document was last modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who last modified the salesliteratureitem.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier of the organization associated with the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public System.Nullable<System.Guid> OrganizationId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the sales literature that is associated with the individual item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesliteratureid")]
		public Microsoft.Xrm.Sdk.EntityReference SalesLiteratureId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("salesliteratureid");
			}
			set
			{
				this.OnPropertyChanging("SalesLiteratureId");
				this.SetAttributeValue("salesliteratureid", value);
				this.OnPropertyChanged("SalesLiteratureId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesliteratureitemid")]
		public System.Nullable<System.Guid> SalesLiteratureItemId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("salesliteratureitemid");
			}
			set
			{
				this.OnPropertyChanging("SalesLiteratureItemId");
				this.SetAttributeValue("salesliteratureitemid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("SalesLiteratureItemId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesliteratureitemid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.SalesLiteratureItemId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Type the title or name that describes the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			set
			{
				this.OnPropertyChanging("Title");
				this.SetAttributeValue("title", value);
				this.OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N SalesLiteratureItem_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesLiteratureItem_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation> SalesLiteratureItem_AsyncOperations
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation>("SalesLiteratureItem_AsyncOperations", null);
			}
			set
			{
				this.OnPropertyChanging("SalesLiteratureItem_AsyncOperations");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.AsyncOperation>("SalesLiteratureItem_AsyncOperations", null, value);
				this.OnPropertyChanged("SalesLiteratureItem_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N SalesLiteratureItem_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesLiteratureItem_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure> SalesLiteratureItem_BulkDeleteFailures
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure>("SalesLiteratureItem_BulkDeleteFailures", null);
			}
			set
			{
				this.OnPropertyChanging("SalesLiteratureItem_BulkDeleteFailures");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.BulkDeleteFailure>("SalesLiteratureItem_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("SalesLiteratureItem_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N salesliteratureitem_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesliteratureitem_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder> salesliteratureitem_MailboxTrackingFolders
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder>("salesliteratureitem_MailboxTrackingFolders", null);
			}
			set
			{
				this.OnPropertyChanging("salesliteratureitem_MailboxTrackingFolders");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.MailboxTrackingFolder>("salesliteratureitem_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("salesliteratureitem_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N salesliteratureitem_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesliteratureitem_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess> salesliteratureitem_PrincipalObjectAttributeAccesses
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess>("salesliteratureitem_PrincipalObjectAttributeAccesses", null);
			}
			set
			{
				this.OnPropertyChanging("salesliteratureitem_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.PrincipalObjectAttributeAccess>("salesliteratureitem_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("salesliteratureitem_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N SalesLiteratureItem_ProcessSessions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SalesLiteratureItem_ProcessSessions")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.ProcessSession> SalesLiteratureItem_ProcessSessions
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ProcessSession>("SalesLiteratureItem_ProcessSessions", null);
			}
			set
			{
				this.OnPropertyChanging("SalesLiteratureItem_ProcessSessions");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.ProcessSession>("SalesLiteratureItem_ProcessSessions", null, value);
				this.OnPropertyChanged("SalesLiteratureItem_ProcessSessions");
			}
		}
		
		/// <summary>
		/// 1:N salesliteratureitem_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("salesliteratureitem_SyncErrors")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.SyncError> salesliteratureitem_SyncErrors
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SyncError>("salesliteratureitem_SyncErrors", null);
			}
			set
			{
				this.OnPropertyChanging("salesliteratureitem_SyncErrors");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.SyncError>("salesliteratureitem_SyncErrors", null, value);
				this.OnPropertyChanged("salesliteratureitem_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N userentityinstancedata_salesliteratureitem
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_salesliteratureitem")]
		public System.Collections.Generic.IEnumerable<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData> userentityinstancedata_salesliteratureitem
		{
			get
			{
				return this.GetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData>("userentityinstancedata_salesliteratureitem", null);
			}
			set
			{
				this.OnPropertyChanging("userentityinstancedata_salesliteratureitem");
				this.SetRelatedEntities<Xrm.Sdk.PluginRegistration.Entities.UserEntityInstanceData>("userentityinstancedata_salesliteratureitem", null, value);
				this.OnPropertyChanged("userentityinstancedata_salesliteratureitem");
			}
		}
		
		/// <summary>
		/// N:1 lk_salesliteratureitem_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesliteratureitem_createdonbehalfby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_salesliteratureitem_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitem_createdonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_salesliteratureitem_createdonbehalfby");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitem_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_salesliteratureitem_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_salesliteratureitem_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesliteratureitem_modifiedonbehalfby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_salesliteratureitem_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitem_modifiedonbehalfby", null);
			}
			set
			{
				this.OnPropertyChanging("lk_salesliteratureitem_modifiedonbehalfby");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitem_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_salesliteratureitem_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_salesliteratureitembase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesliteratureitembase_createdby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_salesliteratureitembase_createdby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitembase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_salesliteratureitembase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_salesliteratureitembase_modifiedby")]
		public Xrm.Sdk.PluginRegistration.Entities.SystemUser lk_salesliteratureitembase_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SystemUser>("lk_salesliteratureitembase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 sales_literature_items
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("salesliteratureid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sales_literature_items")]
		public Xrm.Sdk.PluginRegistration.Entities.SalesLiterature sales_literature_items
		{
			get
			{
				return this.GetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SalesLiterature>("sales_literature_items", null);
			}
			set
			{
				this.OnPropertyChanging("sales_literature_items");
				this.SetRelatedEntity<Xrm.Sdk.PluginRegistration.Entities.SalesLiterature>("sales_literature_items", null, value);
				this.OnPropertyChanged("sales_literature_items");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		public SalesLiteratureItem(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["salesliteratureitemid"] = base.Id;
                        break;
                    case "salesliteratureitemid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filetypecode")]
		public virtual salesliteratureitem_filetypecode? FileTypeCodeEnum
		{
			get
			{
				return ((salesliteratureitem_filetypecode?)(EntityOptionSetEnum.GetEnum(this, "filetypecode")));
			}
			set
			{
				FileTypeCode = value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null;
			}
		}
	}
}